services:
  egc:
    image: nginx:alpine
    container_name: egc
    restart: always
    ports:
      - "3011:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
